/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/K5gXYV0Jtkt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { TableHead, TableRow, TableHeader, TableBody, Table, TableCell } from "@/components/ui/table"
import prisma from "@/lib/prisma"
import AddPersonnelButton from "./add-personnel-button"

export async function AllPersonnelList() {
    const personnels=await prisma.personnel.findMany({});
  return (
    <div className="flex flex-col gap-8">
        <AddPersonnelButton/>
           <div className="bg-white p-6 shadow-md dark:bg-gray-950">
        <h2 className="mb-4 text-2xl font-bold">Personnel List</h2>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Employee BD</TableHead>
              <TableHead>Name</TableHead>
              <TableHead>Branch</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {personnels.map((employee) => (
              <TableRow key={employee.id}>
                <TableCell>{employee.bd}</TableCell>
                <TableCell>{employee.name}</TableCell>
                <TableCell>{employee.branch}</TableCell>
              </TableRow>
            ))}
          </TableBody>
       
        </Table>
      </div>
    </div>
  )
}
