/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kgeURPWKl9j
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"
import { Button } from "@/components/ui/button"
import { DialogTrigger, DialogTitle, DialogDescription, DialogHeader, DialogFooter, DialogContent, Dialog } from "@/components/ui/dialog"
import { Label } from "@/components/ui/label"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { useState } from "react"
import LoadingButton from "../loading-button"

export function StatusUpdateButton({ id }: any) {
  const [status, setStatus] = useState("")
  const [amount, setAmount] = useState("")
  const [loading, setLoading] = useState(false)
  async function handleSubmit() {
    setLoading(true)
    const currentDate = new Date();
    const date = currentDate.toISOString();
    const billData = {
      id,
      ...(amount && { newAmount: amount }),
      newStatus: { date, status }
    };
    const response = await fetch('/api/bills/status', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(billData),
    });

    if (response.ok) {
      console.log('Bill data updated successfully');
    } else {
      console.error('Error saving bill data');
    }
    setLoading(false)
  }
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline">Update Status</Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Update Order Status</DialogTitle>
          <DialogDescription>Select the current status e if needed.</DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="grid items-center grid-cols-2 gap-4">
            <Label htmlFor="status" className="text-right">
              Status
            </Label>
            {/* className="col-span-1" */}
            <Select value={status} onValueChange={setStatus}>
              <SelectTrigger>
                <SelectValue placeholder="Select status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="POR Received">POR Received</SelectItem>
                <SelectItem value="Bill Prepared">Bill Prepared</SelectItem>
                <SelectItem value="Waiting For OIC/OC Sign">Waiting For OIC/OC Sign</SelectItem>
                <SelectItem value="Bill Ready">Bill Ready</SelectItem>
                <SelectItem value="Paid">Paid</SelectItem>
              </SelectContent>
            </Select>
          </div>
          {status === "Bill Prepared" && (
            <div className="grid items-center grid-cols-4 gap-4">
              <Label htmlFor="amount" className="text-right">
                Amount
              </Label>
              <Input onChange={e => setAmount(e.target.value)} id="amount" type="number" className="col-span-3" />
            </div>
          )}
        </div>
        <DialogFooter>
          {/* <Button type="submit" onClick={handleSubmit}>Update</Button> */}
          <LoadingButton loading={loading} type="submit" onClick={handleSubmit}>Update</LoadingButton>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
